### ISSUE TITLE
How to add remarks to the field of the table, and the table header shows the field remarks information

### ISSUE THREAD

**Issue by Caesar454905970** [EinRainerZufall/godot_tree_table#3]
I use fields to match inserts, but I want to display the field's comment information as the table header

**Comment by EinRainerZufall** [comment]
Ok, I think I don't quite understand the question, you want to add comments to fields, e.g. like notes in Excel, and then what should be in the header?

**Comment by Caesar454905970** [comment]
![image](https://github.com/user-attachments/assets/f04d9958-27e7-4fdb-8b73-05ffcfe3c170)

**Comment by Caesar454905970** [comment]
I want to use a different name for the date header to display the header

**Comment by Caesar454905970** [comment]
Can you add a button in a column or double-click a function to trigger a scene jump？

**Comment by EinRainerZufall** [comment]
I have now added a double-click function the Branch [double-click](/EinRainerZufall/godot_tree_table/tree/double-click). Is that what you wanted?
And you want the header to be accessible via a dictionary, in other words?

**Comment by Caesar454905970** [comment]
Double click is what I want, and at the same time, I want the Name to be a Chinese string in the table title, such as "姓名".

**Comment by EinRainerZufall** [comment]
Yes, the header can be freely named. And Godot supports Chinese. 
![Screenshot 2024-09-04 152550](https://github.com/user-attachments/assets/de2544e4-53a6-4adb-b598-882ec6d140c2)

To change the header column, simply add a new entry with the name in the header array.
![Screenshot 2024-09-04 152614](https://github.com/user-attachments/assets/e46afb8a-60fc-41a9-8e07-dd6adf3801a6)

**Comment by Caesar454905970** [comment]
you are right! thank you ! else question，how to add Button or other element as a column ?
![image](https://github.com/user-attachments/assets/788f9e89-4137-4d74-a42e-59e760fd9167)
![image](https://github.com/user-attachments/assets/7cce5dbe-55df-461e-8974-e177ae5bbca9)

**Comment by EinRainerZufall** [comment]
This is not possible at the moment, I have already tried something around with it but have not yet found an implementation that I find nice.

**Comment by Caesar454905970** [comment]
okay! Double click can currently meet my needs.
